import pytest

from riaps_fixtures_library.remote_connection import fabric_group
from riaps_fixtures_library.remote_connection import setup_remote_tmux
from riaps_fixtures_library.LogServer import log_server, platform_log_server
from riaps_fixtures_library.utils import test_logger, mqtt_client