# This is the hosts configuration file for the RIAPS fabfile
[RIAPS]

# List of remote RIAPS hosts for Fabric
# RIAPS nodes can be addressed by their IP address or the hostname.local (found at the command prompt on the RIAPS node)
# If the control machine will host a RIAPS node, include it in both the "nodes" list and the "control" definition.
# For example: nodes = ["192.168.1.2","192.168.1.3","ubuntu.local","riaps-ef9e.local"]
nodes = ["riaps-5eb7.local", "riaps-a702.local", "riaps-adef.local", "riaps-cb60.local", "riaps-c452.local", "riaps-ede8.local", "riaps-99b4.local", "riaps-aab1.local", "riaps-2f37.local", "riaps-11c5.local"]
control = "riaps-VirtualBox.local"
